version: "3"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "pipenv run python src/manage.py migrate
      && pipenv run python src/manage.py runserver 0.0.0.0:8000"
  celery:
    build: .
    command: pipenv run celery worker --app app --beat --workdir src -l info
    volumes:
      - .:/code/
    depends_on:
      - redis
      - web
